version: '3'
services:
  db:
    container_name: fly-go-postgres
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fly_go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fly-go-postgres-data:/var/lib/postgresql/data
    networks:
      - fly-go-network

networks:
  fly-go-network:
    driver: bridge

volumes:
  fly-go-postgres-data:
    driver: local